#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : flake8-import-order
Version  : 0.18
Release  : 1
URL      : https://files.pythonhosted.org/packages/5b/5b/fd248ea91880a7b5e4754f396f4598e8244f28df0d0f8790453acbafc7c4/flake8-import-order-0.18.tar.gz
Source0  : https://files.pythonhosted.org/packages/5b/5b/fd248ea91880a7b5e4754f396f4598e8244f28df0d0f8790453acbafc7c4/flake8-import-order-0.18.tar.gz
Summary  : Flake8 and pylama plugin that checks the ordering of import statements.
Group    : Development/Tools
License  : LGPL-3.0
Requires: flake8-import-order-python3
Requires: flake8-import-order-license
Requires: flake8-import-order-python
Requires: enum34
Requires: pycodestyle
Requires: setuptools
BuildRequires : buildreq-distutils3
BuildRequires : pycodestyle
BuildRequires : setuptools

%description
===================
        
        |Build Status|

%package license
Summary: license components for the flake8-import-order package.
Group: Default

%description license
license components for the flake8-import-order package.


%package python
Summary: python components for the flake8-import-order package.
Group: Default
Requires: flake8-import-order-python3

%description python
python components for the flake8-import-order package.


%package python3
Summary: python3 components for the flake8-import-order package.
Group: Default
Requires: python3-core

%description python3
python3 components for the flake8-import-order package.


%prep
%setup -q -n flake8-import-order-0.18

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1533076537
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/flake8-import-order
cp COPYING %{buildroot}/usr/share/doc/flake8-import-order/COPYING
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(-,root,root,-)
/usr/share/doc/flake8-import-order/COPYING

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
